// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDBwrzCX7rozSJDpAw8kbkVDdayd_lPeA',
    appId: '1:273871393524:web:6edd006b3abb949f21c4a1',
    messagingSenderId: '273871393524',
    projectId: 'flutter-firebase-apps-jgh',
    authDomain: 'flutter-firebase-apps-jgh.firebaseapp.com',
    storageBucket: 'flutter-firebase-apps-jgh.appspot.com',
    measurementId: 'G-C5D7C4DY3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLlPdnhcwzwyMUr4ow0kN-pAQ3EHZI_dc',
    appId: '1:273871393524:android:4f050c937efc337321c4a1',
    messagingSenderId: '273871393524',
    projectId: 'flutter-firebase-apps-jgh',
    storageBucket: 'flutter-firebase-apps-jgh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzJ8fQ9jgM6VxI57ifhIe05inYjwJ7avU',
    appId: '1:273871393524:ios:bc5952b8ddde250221c4a1',
    messagingSenderId: '273871393524',
    projectId: 'flutter-firebase-apps-jgh',
    storageBucket: 'flutter-firebase-apps-jgh.appspot.com',
    iosClientId: '273871393524-57vlf5b2ka1ruka861ks84lsvkj3glq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.techWithTim1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzJ8fQ9jgM6VxI57ifhIe05inYjwJ7avU',
    appId: '1:273871393524:ios:bc5952b8ddde250221c4a1',
    messagingSenderId: '273871393524',
    projectId: 'flutter-firebase-apps-jgh',
    storageBucket: 'flutter-firebase-apps-jgh.appspot.com',
    iosClientId: '273871393524-57vlf5b2ka1ruka861ks84lsvkj3glq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.techWithTim1',
  );
}
